[package]
name = "tui"
version = "0.1.0"
authors = ["spiralClouds <100466805+spiralClouds@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
anyhow = "1.0.96"
